### PR TITLE
RPi instruction updates for 3.9.1

### PR DESCRIPTION
**Pull request by redFrik**
removed the steps for moving GUI files, fixed a serious problem with autostart.sh, removed some unneeded libraries.

### CODE REVIEW

**Comment by redFrik** [comment]
@brianlheim yes, i was wondering this myself, but the `git checkout 3.9` in the instructions seems to somehow get 3.9.1 and this is all not an issue. the gui folders aren't installed, cmake ignores them and the move commands in the instructions can be dropped. i even double checked and line 430 in CMakeLists.txt say `set(SCCLASSLIB_EXCLUDE_REGEX "${SCCLASSLIB_EXCLUDE_REGEX}|GUI")`(here my git ignorance show - why checking out 3.9 wouldn't give me the 3.9 release from a few weeks back i can't understand). so i think my pull request and updates here are adequate. they are tested thoroughly both on full and lite versions of raspbian.

**Comment by brianlheim** [comment]
> why checking out 3.9 wouldn't give me the 3.9 release from a few weeks back i can't understand

3.9 is a branch name, not a version tag. Version tags are (ideally) non-movable, branch refs will point to a new commit every time someone pushes to the branch. You want `git checkout Version-3.9.0`, which is a tag on master. Also, you have to consider that some people may willfully want to build an older version. At the very minimum, please add a note that these instructions are post-3.9.1.

**Comment by brianlheim** [comment]
@redFrik - maybe better to suggest checking out `master` instead of `3.9`? `master` is now stable so the latest commit there will always be the latest released version of SC, so the instructions will never have to change in that regard once we move to 3.10 and above. But maybe you would prefer people get in-development 3.9.x for any unreleased patches?

**Comment by redFrik** [comment]
i'm not sure.  isn't it then hard to know/remember which version you've built and also, for mailing list discussions, being able to track down which instructions someone followed?
but ok - if you say it's a good move for long term stability then master it is. i'll update it later in a separate pull request. this one needs to go in now as there are breaking changes in 3.9.1 and i was requested to adapt ( https://github.com/supercollider/supercollider/pull/3456#issuecomment-361040805 )

**Comment by brianlheim** [comment]
>  isn't it then hard to know/remember which version you've built

The version number is displayed very clearly on startup in the help browser and as output from sclang. You can also find what tag is most recent on your branch using `git describe --tags`.

> being able to track down which instructions someone followed?

I don't follow, sorry.

**Comment by brianlheim** [comment]
This also still needs a notice that the instructions are for verisons >= 3.9.1.

**Comment by redFrik** [comment]
i already added a note about 3.9.x.

**Comment by brianlheim** [comment]
Not the same thing--someone looking at the instructions right now could reasonably assume they apply to earlier versions and try using them to build an older tag.

**Comment by redFrik** [comment]
as i see it, these instructions are good and the main purpose should be to get a working recent sc installed - just like what i've proposed here - i.e. the latest 3.9.x

for that 1% that want to build a specific version i'm sure they can figure it out themselves.  and to have a single set of instruction to cover all versions i'm skeptic of.  too many variables.

**Comment by brianlheim** [comment]
@redFrik I really don't appreciate your stubbornness on what I see as a simple request with obvious benefit for end-users. I'm going to open a separate PR for my changes.

**Pull request merged**
