### PR TITLE
Remove audio examples page and links

### PR DESCRIPTION
**Pull request by patrickdupuis**
This PR removes the **audio examples** page (also linked as **Music**) which contained links to the no longer existant Soundcloud group, the unmaintained Youtube playlist, and to Vimeo where no search results were shown. An unnecessary download link was also removed.

### CODE REVIEW

**Comment by brianlheim** [comment]
Isn't there a sc community thing on soundcloud?

https://soundcloud.com/supercollider-showcase

I'm pretty sure this is it.

**Comment by patrickdupuis** [comment]
Yes - there's that other Soundcloud account that dates back to August 216 (when the groups were taken away). From what I see, it hasn't really been updated much since its creation.

**Comment by brianlheim** [comment]
Still, it's something that exists and documents works made with SC. Idk, I think it's worth pointing to, but your call.

**Comment by patrickdupuis** [comment]
I don't disagree with the idea of keeping this link somewhere on the website, I just want to avoid using it as _the_ official Soundcloud account for SC. It gives the wrong impression if we send people to a dead social media page via a link that says "Here music made with SuperCollider" right in the middle of the homepage.

**Comment by telephon** [comment]
ok, done. Let's see if we can make a page with lots of links ...

**Pull request closed without merging**
