### PR TITLE
download.md: add link to GPG signature

### PR DESCRIPTION
**Pull request by dyfer**

### CODE REVIEW

**Comment by dvzrv** [comment]
Thanks for looking into this in the context of https://github.com/supercollider/supercollider/issues/5533

Would it be possible to e.g. link to a section in the README as well (to clarify the UIDs used for release signatures) as described in https://github.com/supercollider/supercollider/issues/5533#issuecomment-892490365 if this is going to be merged? :)

**Comment by dyfer** [comment]
Sure, if/once we make the changes to the README.
I just wanted to point out, that throughout the 3.11.2 release the link to the signature [was incorrect](https://github.com/supercollider/supercollider.github.io/commit/4e8166e11f2c9e0bd0e5cdcb136de3ded29524e5#diff-1a045c5df256c04b78183c4f92345534f6c0cc193b0bd5f5fd3264d715266a25L61) and nobody complained, so maybe the downloads page is not the place where users look for such information...?

**Comment by dyfer** [comment]
I'd suggest to add this as is and add the requested link after the changes are done to the README. What do you think @dvzrv ?

**Comment by dyfer** [comment]
I'm closing this as we have released 3.12.1 and the signature will be included on the downloads page. To address linking to README, feel free to follow up in https://github.com/supercollider/supercollider/issues/5534

**Pull request closed without merging**
