### PR TITLE
Update SC description

### PR DESCRIPTION
**Pull request by vivid-synth**
Discussed here: https://github.com/supercollider/supercollider/issues/2263

### CODE REVIEW

**Comment by snappizz** [comment]
This doesn't flow too well into the next sentence, which effectively repeats the content.

I have been working on a rewrite of the website description for a little while. Here's what I suggest:

> SuperCollider is a platform for audio synthesis and algorithmic composition. It is used by musicians, artists, and researchers working with sound. It features three major components:
>
> - scsynth, a real-time audio server. scsynth is a "virtual modular synthesizer" that supports anything from standard electronic music fare (subtractive, additive, FM, granular) to any exotic method of synthesis, analysis, and processing you can think of.
> - sclang, an interpreted programming language that controls scsynth via Open Sound Control. sclang boasts a powerful "patterns" system for algorithmic composition. It also allows you to connect your app to external hardware such as MIDI controllers, or write GUIs and visual displays.
> - scide, an editor for sclang with an integrated help system.
>
> SuperCollider is free and open source software available for Windows, Mac OS X, and Linux, available under the terms of the GNU General Public License.

I tried to gear the descriptions toward a more musical crowd. What do you think?

**Comment by vivid-synth** [comment]
Looks great to me, other than I'd also mention supernova

**Comment by snappizz** [comment]
We could add this to the scsynth bullet point:

> An alternative server, supernova, adds optimizations for parallel processing on devices with multicore CPUs.

However, I'm unsure if the average musician is really interested in that distinction. I think a good plan of action is to elaborate in a longer About page, which can go into more technical details.

**Comment by crucialfelix** [comment]
I don't think the next 3 lines repeat the content so much as elaborate on it. Looks fine to me.

**Comment by crucialfelix** [comment]
"virtual modular synthesizer" suggests to me that it is a collection of tone generators and has a wiring system. Like some sort of VST/AU plug in with an API.

"sclang boasts a powerful "patterns" system for algorithmic composition." I would rather have a sentence that lists a few different included systems. many people don't use patterns at all. 

However I think it's good to rewrite those and you are going in the right direction.

Maybe the language features list (further down the page) could emphasize the major music library features (patterns, scales, tuning systems, scheduling). Right now it is too technical about the language itself (I copied stuff from wikipedia and audiosynth.com)

**Comment by crucialfelix** [comment]
I think we should merge this now and then do further rewrites.

**Comment by snappizz** [comment]
Sure, let's merge. I'll open another PR for my proposal.

**Comment by crucialfelix** [comment]
this list: (subtractive, additive, FM, granular) can be longer and more informational (oscillators, filters, FM, granular, FFT, convolution, transient shaping, ... )

I think musicians don't need to have it dumbed down so much: "exotic method of synthesis, analysis, and processing you can think of" - if they came to look at supercollider then they are comparing it to max/msp, pd, soundhack, kyma etc. and they want a quick list of those juicy exotic things. Let's let them know right away that there are many community contributed UGens and that they can write their own in C++.  List the number of UGens.

Let's also list the current number of Quarks; mention that is very active and everything is on github.

Rather than "anything you can imagine !" let's say "look at all this stuff you get .. for free !" which is how musicians really think. We like to acquire and hoard gear/software.

**Comment by snappizz** [comment]
cool, thanks for shopping this. continued at #74.

**Pull request merged**
