### PR TITLE
Add CI for pull requests

### PR DESCRIPTION
**Pull request by capital-G**
Maybe it is good to build the website on each request, just to be aware if it breaks anything.
Especially useful in combination with #282

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks @capital-G 
I like the idea, but how practical is it to check the website from the raw html files? When opened locally, images etc don't get loaded so the only thing that can be checked is text, but it looks off anyway.
I wonder if there's a way to temporarily serve the website online - probably not or not a good idea anyway...

**Comment by capital-G** [comment]
If you serve the directory via e.g. `python3 -m http.server` one can see the images, though the links are not working correctly (`http://127.0.0.1:8000/projects` does not get forwarded to the actual page `http://127.0.0.1:8000/projects.html`).

I think it is maybe less about verifying the actual website but having a build pipeline in case some dependencies must be upgraded via dependabot - but having the ability to verify some changes locally w/o building locally could still be interesting.

**Comment by dyfer** [comment]
Got it. Okay, I see it being useful then.
Would you mind adding some kind of identifier (commit SHA? short SHA?) to the artifact filename? Also, the name could be more indicative than "artifact". Even if the primary use case is not the artifact, I think it would be great if it has a discerning name (with SHA).

**Comment by capital-G** [comment]
Added the SHA of the commit to the artifact name. If this gets merged, it should be squashed.

**Review by telephon — APPROVED** [review]

**Pull request merged**
