### PR TITLE
Use the Jekyll 3 default Rouge syntax highlighter instead of pygments

### PR DESCRIPTION
**Pull request by howthebodyworks**
The Gemfile we have will give us Jekyll 3.1.2, which has altered syntax highlighting since version 2 to default to rouge. see https://jekyllrb.com/docs/upgrading/2-to-3/#syntax-highlighter-changed

We only use the Javascript syntax, so we may as well use the built-in rouge syntax highlighter rather than introducing delicate python dependencies to use the pygments one, since they both support javascript well. (And in any case if you try to use pygments you get a confusing and useless error if you happen to have python 3 installed, at least on my OSX machine)

### CODE REVIEW

**Comment by crucialfelix** [comment]
Great, thanks ! 

Actually pygments now supports supercollider so we can switch the code blocks to that http://pygments.org/docs/lexers/#lexer-for-supercollider

rouge doesn't seem to have that:
https://github.com/jneen/rouge

**Comment by crucialfelix** [comment]
the python stuff is indeed annoying, even to an old snake like myself.

I highly recommend [Anaconda](https://docs.continuum.io/anaconda/index) which lets you switch python versions like rvm and create separate environments to install packages in.

Specifically install the miniconda version that just has the switching and ability to create environments:
http://conda.pydata.org/miniconda.html but doesn't include the 150 packages you will never use.

**Comment by howthebodyworks** [comment]
nono, thank YOU

Ah wow I didn't notice the SC highlighting in pygments.

OK, to summarise, we need to choose something from the following list (did i get everything?):

1. pygments with full SC support (I'm assuming the quality of this support is good?)
2. rouge, with JS support only (Where we know the quality of highlighting is only as good as a JS highlighter can be for non-JS code)
3. rouge, but we contribute an SC highlighter to rouge

Whatever we choose, should probably document it in the wiki too.

For this commit I was thinking purely in terms of ease of contribution to the wiki for someone who doesn't give two hoots about ruby or python but wants to document something about the SC+SC community in markdown and has bothered to navigate the already forbidding forests of pull requests...

Right now it's an unsatisfactory experience for that hypothetical user, having to learn both ruby's bundler and a python virtualenv management system, conda or pip or whatever, and possibly even the difference between python 2 and 3, just to post their blog link.

My intuition would be that making do with rouge's inferior syntax highlighting would be an appropriate sacrifice to make to get 'em in, but I would also be happy to submit a "install miniconda+pygments" doc update instead. Realistically I am unlikely to implement option 3, syntax highlighters in ruby, which is not a language I know a bunch about.

What do you reckon we need here?

**Comment by crucialfelix** [comment]
this guy did it:
https://twitter.com/colinsullivan
If I remember correctly he actually works for either github or travis, and
he's a music coder and sc user

It may be mostly a js clone:
https://bitbucket.org/birkenfeld/pygments-main/issues/731/feature-request-supercollider

---

> just to post their blog link.

ah but you can just click "edit this page" at the bottom and just change
the markdown file on github.
it submits a pull request. no need to checkout the whole site at all.


---

We should probably move all the wiki pages to the github wiki and leave the
site to be just a simple site.




On Mon, Mar 21, 2016 at 11:10 AM dan mackinlay <notifications@github.com>
wrote:

> nono, thank YOU
>
> Ah wow I didn't notice the SC highlighting in pygments.
>
> OK, to summarise, we need to choose something from the following list (did
> i get everything?):
>
>    1. pygments with full SC support (I'm assuming the quality of this
>    support is good?)
>    2. rouge, with JS support only (Where we know the quality of
>    highlighting is only as good as a JS highlighter can be for non-JS code)
>    3. rouge, but we contribute an SC highlighter to rouge
>
> Whatever we choose, should probably document it in the wiki too.
>
> For this commit I was thinking purely in terms of ease of contribution to
> the wiki for someone who doesn't give two hoots about ruby or python but
> wants to document something about the SC+SC community in markdown and has
> bothered to navigate the already forbidding forests of pull requests...
>
> Right now it's an unsatisfactory experience for that hypothetical user,
> having to learn both ruby's bundler and a python virtualenv management
> system, conda or pip or whatever, and possibly even the difference between
> python 2 and 3, just to post their blog link.
>
> My intuition would be that making do with rouge's inferior syntax
> highlighting would be an appropriate sacrifice to make to get 'em in, but I
> would also be happy to submit a "install miniconda+pygments" doc update
> instead. Realistically I am unlikely to implement option 3, syntax
> highlighters in ruby, which is not a language I know a bunch about.
>
> What do you reckon we need here?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider.github.io/pull/54#issuecomment-199210276>
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by crucialfelix** [comment]
See this example page:

https://github.com/supercollider/supercollider.github.io/blob/master/contributing/syntax-and-styling.md

it works !

**Comment by howthebodyworks** [comment]
>  We should probably move all the wiki pages to the github wiki and leave the
site to be just a simple site.
 
Ah!

Right, I didn't include the gh-wiki option, although I have tried it.

FWIW, we tried github wiki on another project a year or two ago but ultimately ditched it because, IIRC

1. Styling was tedious
2. [Image/audio uploads were onerous](https://help.github.com/articles/adding-images-to-wikis/) requiring you to checkout the site and put them in the repository, negating the ease of the online wiki editing.
3. IIRC you can't use the github wiki as a github pages site so we had a github wiki and a github pages site, and it wasn't clear what was wiki content and what was site content and we ended up duplicating heaps of content, having a developer-only merge workflow and shouting at each other.
4. no one looks at the github wiki, which is buried in navigation, compared with the friendly TLD yo can give a gh-pages site.

I imagine SC might have similar experience?

>> just to post their blog link.
> ah but you can just click "edit this page" at the bottom and just change
> the markdown file on github.
> it submits a pull request. no need to checkout the whole site at all.

Yes, now that is a very fine point indeed.
Maybe we should just document in the how-to-contribute page, making this entire thing basically a documentation request, and chalk it down to my overzealous developer instincts to fork codebases and mess around when I should be doing something else.

I'd vote to keep the github-pages jekyll site as the main wiki FWIW;  it's more friendly, accessible and self-promotion-friendly than the inscrutable and hidden github-wiki. But the other bit - where you point out that we can just rely on github to do everything for us whether in a gh-pages or gh-wiki site, I like that one, and it suggests a solution of us doing barely anything, which is an excellent solution.

**Comment by crucialfelix** [comment]
maybe just increase the edit link or move it up out of the footer.

you aren't the first to not notice it.

I agree with 4. - the other wiki pages are buried. but they are great for fast editing of technical pages. people don't bother to post on the site, its too formal of a process.

**Comment by bagong** [comment]
I locally get an error with the configuration setting

    pygments: true

It has now to be

    highlighter: pygments

Might that be the reason why the site is showing a build error since a week or so? @redFrik 's changes to the Raspi build are committed, but don't show up in the live site.

Side remark: I spent a frustrating 2 hours trying to get Jekyll running on my Mac. This python stuff is confusing, and ruby/gem and jekyll versions have to match in some undocumented way, otherwise jekyll will not see gems you install. I only got it to work after I installed ruby 2.3 via homebrew (replacing the default Mac one, which is 2.0, so *should* be good enough for Jekyll 3), reinstalled Jekyll and updated all gems to the latest (as installed by the new ruby version). So it works now. But this also means I locally have Jekyll 3.1.3 while Github seems to use 3.0.5... so another potential problem...

**Comment by bagong** [comment]
@howthebodyworks , is that ruby 2.0 directive necessary/good? I don't understand what it does, but on a Mac using ruby 2.0 didn't allow jekyll to work properly...

**Comment by howthebodyworks** [comment]
@bagong, see #53. the ruby 2.0.0 directive means that you need ruby 2.0.0, not ruby 1.9.x or 2.0.1 or any other version. So it's bad. Jekyll runs on many versions, such as my ruby 2.3.1 homebrew install. However, @crucialfelix  already merged the change removing that 2.0.0 requirement, so it should no longer be an issue. Check you are working from the latest version.

As for easy editing, I agree that jekyll can be annoying; there are various editors such as [prose.io](http://prose.io/), [cactus](http://cactusformac.com/) and [gitbook](https://www.gitbook.com/) that make it easier in various ways.

This ticket is more about the fact that combining python and ruby to render a site is even _more_ complex (and at time of writing we weren't even benefiting from it)

**Comment by crucialfelix** [comment]
Superseded by @bagong's attempt to get pygments to work that is now merged. We still don't have the syntax highlighting. 

Thanks @howthebodyworks for the PR; it and the discussion helped.

**Comment by bagong** [comment]
I now know that curently Github hardcodes rouge as highlighter. That whole line does nothing, and setting it to someting else than rouge produces those warning emails.
I guess for now the only way would be to contribute a lexer to rouge...

**Pull request closed without merging**
