### PR TITLE
Revert code highlighting

### PR DESCRIPTION
**Pull request by patrickdupuis**
Let's revert this back to how it was previously.

### CODE REVIEW

**Comment by telephon** [comment]
Can you briefly state why? it doesn't work?

**Comment by telephon** [comment]
It should work:

https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by patrickdupuis** [comment]
Sorry, I though this would be clear considering the last PR. Currently, we do not have a better option than this for code blocks. We can improve upon things later. For now, let's please revert this back to the way it was.

**Comment by brianlheim** [comment]
Highlighting on GitHub pages via Jekyll uses Rouge. Highlighting on GitHub uses Linguist. They are different services (No idea why). I submitted a PR to Rouge to add SuperCollider support, they have not merged it in 6 months despite the project owner saying it's ready.

**Comment by brianlheim** [comment]
The only way to get actual SC highlighting would be to take my PR and run it locally so that the code blocks are highlighted via html tags, but it would be messy and add another step to the process, I don't think it's worth it right now.

**Pull request merged**
