### PR TITLE
Update systems-interfacing-with-sc.md

### PR DESCRIPTION
**Pull request by ventosus**
* add link to Chimaera project, which can directly connect to SuperCollider server

### CODE REVIEW

**Comment by crucialfelix** [comment]
That looks really interesting. I might even get one of those!

**Comment by ventosus** [comment]
I'm looking for Beta testers...

**Comment by crucialfelix** [comment]
how high up can you have your hands ? I've been looking for some controller that is super sensitive like this

**Comment by ventosus** [comment]
Depends on the strength/size of the permanent magnet and the amplification factor.

Magnetic field strength of a permanent magnet decreases by the cube (roughly) with distance.
The type of sensors I use measure in the range of -400..400 Gauss.
There's a built-in amplification circuitry (1x..10x) which can boost the measurable range up to -4000..4000 Gauss.

I have my device calibrated for a depth of 15-20mm for a 20x4x3mm magnet, which I found to be the ideal compromise for both percussive and expressive play.

If you want more depth, you can increase the amplification factor on the hardware itself and/or use stronger/bigger magnets. As distance-magnetic field strength relationship is not linear, magnets get bulky fastly. I have only tested the design for a depth of up to 40-50mm which is already somewhat impractical for a percussive play as the distance for event retriggering is too high for my taste.

Here an online calculator which shows the relationships nicely (use N45 as the grade).
https://www.kjmagnetics.com/calculator.asp?calcType=block

**Pull request merged**
